### ISSUE TITLE
Combination should (probably) use a different variable for its definition

### ISSUE THREAD

**Issue by alanbchristie** [InformaticsMatters/fragmentor#5]
Currently the **combination** playbook uses the data structure called `extracts`, which is shared with the **extract** playbook but here the field names are different. i.e. the structure for the **extract** play is typically: -

```yaml
extracts:
- lib:
    vendor: 'molport'
    version: '2020-10'
    regenerate_index: yes
```

But for **combination** the structure is: -

```yaml
extracts:
- lib:
    path: 'xchem_dsip'
    data_source: disk
- lib:
    path: 'extract/xchem_spot/v1'
    data_source: s3
    bucket: "{{ bucket_in_1 }}"
    aws_access_key: "{{ aws_access_key_in_1 }}"
    aws_secret_key: "{{ aws_secret_key_in_1 }}"
```

To provide better integration with the **extract** play (i.e. allow for a single parameter file to define the whole process and avoid using one variable for very different tasks) the **combination** stage should probably use a dedicated data structure called `combinations` rather than re-using `extracts`?
